version: '3.1'

services:
  nxplx-database:
    image: bitnami/postgresql:13
    environment:
      - POSTGRESQL_PASSWORD=dev
    ports:
      - "5432:5432"
      
  nxplx-cache:
    image: bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD=dev
      - REDIS_AOF_ENABLED=no
    ports:
      - "6379:6379"

  nxplx-logs:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5342:80"
      - "5341:5341"