// This file is automatically generated from your CSS. Any edits will be overwritten.
export const header: string;
export const menu: string;
export const menuContent: string;
export const menuOpener: string;
