// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        bottomControls: string;
        centerPlayButton: string;
        closeButton: string;
        focused: string;
        hover: string;
        loaded: string;
        range: string;
        title: string;
        topControls: string;
        touch: string;
        track: string;
        video: string;
        videoContainer: string;
        videoControls: string;
        volumeControls: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
