// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        video: string;
        videoContainer: string;
        videoControls: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
