// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        bottomControls: string;
        focused: string;
        playing: string;
        title: string;
        topControls: string;
        touch: string;
        video: string;
        videoContainer: string;
        videoControls: string;
        volumeControls: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
