// This file is automatically generated from your CSS. Any edits will be overwritten.
export const bg: string;
export const poster: string;
export const play: string;
export const playPosterContainer: string;
export const title: string;
export const tag: string;
export const info: string;
export const marked: string;
export const infoKey: string;
export const infoValue: string;
