// This file is automatically generated from your CSS. Any edits will be overwritten.
export const home: string;
export const entryContainer: string;
export const entryTile: string;
export const search: string;
export const scan: string;
export const top: string;
export const continueWatching: string;
