// This file is automatically generated from your CSS. Any edits will be overwritten.
export const loadingContainer: string;
export const skFoldingCube: string;
export const skCube: string;
export const skFoldCubeAngle: string;
export const skCube2: string;
export const skCube3: string;
export const skCube4: string;
