// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        loadingContainer: string;
        "sk-cube": string;
        "sk-cube2": string;
        "sk-cube3": string;
        "sk-cube4": string;
        "sk-foldCubeAngle": string;
        "sk-folding-cube": string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
