// This file is automatically generated from your CSS. Any edits will be overwritten.
export const modal: string;
export const modalRoot: string;
export const open: string;
export const dialog: string;
export const header: string;
export const content: string;
