// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        content: string;
        dialog: string;
        header: string;
        modal: string;
        modalRoot: string;
        open: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
