// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NxPlx.Infrastructure.Database;

namespace NxPlx.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201123225915_UseImplicitJoinEntities")]
    partial class UseImplicitJoinEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CreatorDbSeriesDetails", b =>
                {
                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedSeriesId")
                        .HasColumnType("integer");

                    b.HasKey("CreatedById", "CreatedSeriesId");

                    b.HasIndex("CreatedSeriesId");

                    b.ToTable("CreatorDbSeriesDetails");
                });

            modelBuilder.Entity("DbFilmDetailsGenre", b =>
                {
                    b.Property<int>("FilmInGenreId")
                        .HasColumnType("integer");

                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.HasKey("FilmInGenreId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("DbFilmDetailsGenre");
                });

            modelBuilder.Entity("DbFilmDetailsProductionCompany", b =>
                {
                    b.Property<int>("ProducedFilmId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionCompaniesId")
                        .HasColumnType("integer");

                    b.HasKey("ProducedFilmId", "ProductionCompaniesId");

                    b.HasIndex("ProductionCompaniesId");

                    b.ToTable("DbFilmDetailsProductionCompany");
                });

            modelBuilder.Entity("DbFilmDetailsProductionCountry", b =>
                {
                    b.Property<int>("FilmedOnLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductionCountriesIso3166_1")
                        .HasColumnType("text");

                    b.HasKey("FilmedOnLocationId", "ProductionCountriesIso3166_1");

                    b.HasIndex("ProductionCountriesIso3166_1");

                    b.ToTable("DbFilmDetailsProductionCountry");
                });

            modelBuilder.Entity("DbFilmDetailsSpokenLanguage", b =>
                {
                    b.Property<int>("SpokenInFilmId")
                        .HasColumnType("integer");

                    b.Property<string>("SpokenLanguagesIso639_1")
                        .HasColumnType("text");

                    b.HasKey("SpokenInFilmId", "SpokenLanguagesIso639_1");

                    b.HasIndex("SpokenLanguagesIso639_1");

                    b.ToTable("DbFilmDetailsSpokenLanguage");
                });

            modelBuilder.Entity("DbSeriesDetailsGenre", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesInGenreId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "SeriesInGenreId");

                    b.HasIndex("SeriesInGenreId");

                    b.ToTable("DbSeriesDetailsGenre");
                });

            modelBuilder.Entity("DbSeriesDetailsNetwork", b =>
                {
                    b.Property<int>("AiredSeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("NetworksId")
                        .HasColumnType("integer");

                    b.HasKey("AiredSeriesId", "NetworksId");

                    b.HasIndex("NetworksId");

                    b.ToTable("DbSeriesDetailsNetwork");
                });

            modelBuilder.Entity("DbSeriesDetailsProductionCompany", b =>
                {
                    b.Property<int>("ProducedSeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionCompaniesId")
                        .HasColumnType("integer");

                    b.HasKey("ProducedSeriesId", "ProductionCompaniesId");

                    b.HasIndex("ProductionCompaniesId");

                    b.ToTable("DbSeriesDetailsProductionCompany");
                });

            modelBuilder.Entity("NxPlx.Models.Database.DbFilmDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Adult")
                        .HasColumnType("boolean");

                    b.Property<string>("BackdropBlurHash")
                        .HasColumnType("text");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text");

                    b.Property<int?>("BelongsInCollectionId")
                        .HasColumnType("integer");

                    b.Property<long>("Budget")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<float>("Popularity")
                        .HasColumnType("real");

                    b.Property<string>("PosterBlurHash")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("Revenue")
                        .HasColumnType("bigint");

                    b.Property<int?>("Runtime")
                        .HasColumnType("integer");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<float>("VoteAverage")
                        .HasColumnType("real");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BelongsInCollectionId");

                    b.ToTable("FilmDetails");
                });

            modelBuilder.Entity("NxPlx.Models.Database.DbSeriesDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("BackdropBlurHash")
                        .HasColumnType("text");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FirstAirDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("InProduction")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAirDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<double>("Popularity")
                        .HasColumnType("double precision");

                    b.Property<string>("PosterBlurHash")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<double>("VoteAverage")
                        .HasColumnType("double precision");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SeriesDetails");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Film.MovieCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("BackdropBlurHash")
                        .HasColumnType("text");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PosterBlurHash")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MovieCollection");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Film.ProductionCountry", b =>
                {
                    b.Property<string>("Iso3166_1")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Iso3166_1");

                    b.ToTable("ProductionCountry");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Film.SpokenLanguage", b =>
                {
                    b.Property<string>("Iso639_1")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Iso639_1");

                    b.ToTable("SpokenLanguage");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("NxPlx.Models.Details.ProductionCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoBlurHash")
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OriginCountry")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ProductionCompany");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Series.Creator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Creator");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Series.EpisodeDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("ProductionCode")
                        .HasColumnType("text");

                    b.Property<int>("SeasonDetailsId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("StillBlurHash")
                        .HasColumnType("text");

                    b.Property<string>("StillPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<float>("VoteAverage")
                        .HasColumnType("real");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonDetailsId");

                    b.ToTable("EpisodeDetails");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Series.Network", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoBlurHash")
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OriginCountry")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Network");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Series.SeasonDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DbSeriesDetailsId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("PosterBlurHash")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DbSeriesDetailsId");

                    b.ToTable("SeasonDetails");
                });

            modelBuilder.Entity("NxPlx.Models.File.EpisodeFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastWrite")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PartOfLibraryId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("SeriesDetailsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartOfLibraryId");

                    b.HasIndex("SeasonNumber");

                    b.HasIndex("SeriesDetailsId");

                    b.ToTable("EpisodeFiles");
                });

            modelBuilder.Entity("NxPlx.Models.File.FilmFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("FilmDetailsId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastWrite")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PartOfLibraryId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilmDetailsId");

                    b.HasIndex("PartOfLibraryId");

                    b.ToTable("FilmFiles");
                });

            modelBuilder.Entity("NxPlx.Models.File.SubtitleFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EpisodeFileId")
                        .HasColumnType("integer");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("FilmFileId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastWrite")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeFileId");

                    b.HasIndex("FilmFileId");

                    b.ToTable("SubtitleFiles");
                });

            modelBuilder.Entity("NxPlx.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("NxPlx.Models.SubtitlePreference", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.HasKey("UserId", "FileId", "MediaType");

                    b.HasIndex("FileId");

                    b.HasIndex("MediaType");

                    b.HasIndex("UserId");

                    b.ToTable("SubtitlePreferences");
                });

            modelBuilder.Entity("NxPlx.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Admin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("HasChangedPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("LibraryAccessIds")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UpdatedCorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NxPlx.Models.WatchingProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastWatched")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Time")
                        .HasColumnType("double precision");

                    b.HasKey("UserId", "FileId", "MediaType");

                    b.HasIndex("FileId");

                    b.HasIndex("MediaType");

                    b.HasIndex("UserId");

                    b.ToTable("WatchingProgresses");
                });

            modelBuilder.Entity("CreatorDbSeriesDetails", b =>
                {
                    b.HasOne("NxPlx.Models.Details.Series.Creator", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NxPlx.Models.Database.DbSeriesDetails", null)
                        .WithMany()
                        .HasForeignKey("CreatedSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbFilmDetailsGenre", b =>
                {
                    b.HasOne("NxPlx.Models.Database.DbFilmDetails", null)
                        .WithMany()
                        .HasForeignKey("FilmInGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NxPlx.Models.Details.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbFilmDetailsProductionCompany", b =>
                {
                    b.HasOne("NxPlx.Models.Database.DbFilmDetails", null)
                        .WithMany()
                        .HasForeignKey("ProducedFilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NxPlx.Models.Details.ProductionCompany", null)
                        .WithMany()
                        .HasForeignKey("ProductionCompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbFilmDetailsProductionCountry", b =>
                {
                    b.HasOne("NxPlx.Models.Database.DbFilmDetails", null)
                        .WithMany()
                        .HasForeignKey("FilmedOnLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NxPlx.Models.Details.Film.ProductionCountry", null)
                        .WithMany()
                        .HasForeignKey("ProductionCountriesIso3166_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbFilmDetailsSpokenLanguage", b =>
                {
                    b.HasOne("NxPlx.Models.Database.DbFilmDetails", null)
                        .WithMany()
                        .HasForeignKey("SpokenInFilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NxPlx.Models.Details.Film.SpokenLanguage", null)
                        .WithMany()
                        .HasForeignKey("SpokenLanguagesIso639_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbSeriesDetailsGenre", b =>
                {
                    b.HasOne("NxPlx.Models.Details.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NxPlx.Models.Database.DbSeriesDetails", null)
                        .WithMany()
                        .HasForeignKey("SeriesInGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbSeriesDetailsNetwork", b =>
                {
                    b.HasOne("NxPlx.Models.Database.DbSeriesDetails", null)
                        .WithMany()
                        .HasForeignKey("AiredSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NxPlx.Models.Details.Series.Network", null)
                        .WithMany()
                        .HasForeignKey("NetworksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbSeriesDetailsProductionCompany", b =>
                {
                    b.HasOne("NxPlx.Models.Database.DbSeriesDetails", null)
                        .WithMany()
                        .HasForeignKey("ProducedSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NxPlx.Models.Details.ProductionCompany", null)
                        .WithMany()
                        .HasForeignKey("ProductionCompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NxPlx.Models.Database.DbFilmDetails", b =>
                {
                    b.HasOne("NxPlx.Models.Details.Film.MovieCollection", "BelongsInCollection")
                        .WithMany("Movies")
                        .HasForeignKey("BelongsInCollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BelongsInCollection");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Series.EpisodeDetails", b =>
                {
                    b.HasOne("NxPlx.Models.Details.Series.SeasonDetails", null)
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NxPlx.Models.Details.Series.SeasonDetails", b =>
                {
                    b.HasOne("NxPlx.Models.Database.DbSeriesDetails", null)
                        .WithMany("Seasons")
                        .HasForeignKey("DbSeriesDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NxPlx.Models.File.EpisodeFile", b =>
                {
                    b.HasOne("NxPlx.Models.Library", "PartOfLibrary")
                        .WithMany()
                        .HasForeignKey("PartOfLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NxPlx.Models.Database.DbSeriesDetails", "SeriesDetails")
                        .WithMany()
                        .HasForeignKey("SeriesDetailsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("NxPlx.Models.File.MediaDetails", "MediaDetails", b1 =>
                        {
                            b1.Property<int>("EpisodeFileId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .UseIdentityByDefaultColumn();

                            b1.Property<int>("AudioBitrate")
                                .HasColumnType("integer");

                            b1.Property<string>("AudioChannelLayout")
                                .HasColumnType("text");

                            b1.Property<string>("AudioCodec")
                                .HasColumnType("text");

                            b1.Property<int>("AudioStreamIndex")
                                .HasColumnType("integer");

                            b1.Property<float>("Duration")
                                .HasColumnType("real");

                            b1.Property<string>("VideoAspectRatio")
                                .HasColumnType("text");

                            b1.Property<int>("VideoBitDepth")
                                .HasColumnType("integer");

                            b1.Property<int>("VideoBitrate")
                                .HasColumnType("integer");

                            b1.Property<string>("VideoCodec")
                                .HasColumnType("text");

                            b1.Property<float>("VideoFrameRate")
                                .HasColumnType("real");

                            b1.Property<int>("VideoHeight")
                                .HasColumnType("integer");

                            b1.Property<int>("VideoWidth")
                                .HasColumnType("integer");

                            b1.HasKey("EpisodeFileId");

                            b1.ToTable("EpisodeFiles");

                            b1.WithOwner()
                                .HasForeignKey("EpisodeFileId");
                        });

                    b.Navigation("MediaDetails");

                    b.Navigation("PartOfLibrary");

                    b.Navigation("SeriesDetails");
                });

            modelBuilder.Entity("NxPlx.Models.File.FilmFile", b =>
                {
                    b.HasOne("NxPlx.Models.Database.DbFilmDetails", "FilmDetails")
                        .WithMany()
                        .HasForeignKey("FilmDetailsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NxPlx.Models.Library", "PartOfLibrary")
                        .WithMany()
                        .HasForeignKey("PartOfLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NxPlx.Models.File.MediaDetails", "MediaDetails", b1 =>
                        {
                            b1.Property<int>("FilmFileId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .UseIdentityByDefaultColumn();

                            b1.Property<int>("AudioBitrate")
                                .HasColumnType("integer");

                            b1.Property<string>("AudioChannelLayout")
                                .HasColumnType("text");

                            b1.Property<string>("AudioCodec")
                                .HasColumnType("text");

                            b1.Property<int>("AudioStreamIndex")
                                .HasColumnType("integer");

                            b1.Property<float>("Duration")
                                .HasColumnType("real");

                            b1.Property<string>("VideoAspectRatio")
                                .HasColumnType("text");

                            b1.Property<int>("VideoBitDepth")
                                .HasColumnType("integer");

                            b1.Property<int>("VideoBitrate")
                                .HasColumnType("integer");

                            b1.Property<string>("VideoCodec")
                                .HasColumnType("text");

                            b1.Property<float>("VideoFrameRate")
                                .HasColumnType("real");

                            b1.Property<int>("VideoHeight")
                                .HasColumnType("integer");

                            b1.Property<int>("VideoWidth")
                                .HasColumnType("integer");

                            b1.HasKey("FilmFileId");

                            b1.ToTable("FilmFiles");

                            b1.WithOwner()
                                .HasForeignKey("FilmFileId");
                        });

                    b.Navigation("FilmDetails");

                    b.Navigation("MediaDetails");

                    b.Navigation("PartOfLibrary");
                });

            modelBuilder.Entity("NxPlx.Models.File.SubtitleFile", b =>
                {
                    b.HasOne("NxPlx.Models.File.EpisodeFile", null)
                        .WithMany("Subtitles")
                        .HasForeignKey("EpisodeFileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NxPlx.Models.File.FilmFile", null)
                        .WithMany("Subtitles")
                        .HasForeignKey("FilmFileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NxPlx.Models.SubtitlePreference", b =>
                {
                    b.HasOne("NxPlx.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NxPlx.Models.WatchingProgress", b =>
                {
                    b.HasOne("NxPlx.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NxPlx.Models.Database.DbSeriesDetails", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Film.MovieCollection", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("NxPlx.Models.Details.Series.SeasonDetails", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("NxPlx.Models.File.EpisodeFile", b =>
                {
                    b.Navigation("Subtitles");
                });

            modelBuilder.Entity("NxPlx.Models.File.FilmFile", b =>
                {
                    b.Navigation("Subtitles");
                });
#pragma warning restore 612, 618
        }
    }
}
