// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        autosize: string;
        entry: string;
        link: string;
        progress: string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
