// This file is automatically generated from your CSS. Any edits will be overwritten.
export const bg: string;
export const content: string;
export const poster: string;
export const title: string;
export const info: string;
export const marked: string;
