name: CI - Backend

on:
  push:
    branches:
      - master
    paths:
    - 'nxplx-backend/**'
  pull_request:
    branches:
      - master
      - release
    paths:
    - 'nxplx-backend/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      working-directory: ./nxplx-backend
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cancel outdated workflow-runs
      uses: fkirc/skip-duplicate-actions@master

    - name: Prepare .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Test with dotnet
      working-directory: ${{env.working-directory}}
      run: dotnet test NxPlx.sln --logger GitHubActions